### PR TITLE
Localised Strings in addition to Locale.preferredLanguages

### PR DESCRIPTION
**Pull request by tomlokhorst**
Adds optional `preferredLanguages` parameter to generated strings functions. Used as a replacement for `Locale.preferredLanguages`.

Usage:

```swift
// Assuming the app is localised in English and French
// Returns French localisation, even if Phone is set to English
let hello = R.string.welcome.hello(preferredLanguages: ["nl", "fr"])
```

Fixes https://github.com/mac-cain13/R.swift/issues/219

### CODE REVIEW

**Comment by tomlokhorst** [comment]
Note: As of iOS 13, end users can select the preferred language for an app in Settings.

**Comment by abdelmagied94** [comment]
@tomlokhorst Could we set the preferred language in general instead of insert it in each call?

**Comment by tomlokhorst** [comment]
No, that's not possible with this API.

**Comment by abdelmagied94** [comment]
@tomlokhorst Thanks for your response! In my app, I let the user choose the language he wants in the start of the app. Therefore, I try to find a way to make this the default localization language. I see you set the `applicationLocale` with the first preferred language. Couldn't we set it dynamic?

**Comment by IharAndreyeu** [comment]
Would be great if preferredLanguages: would be a method of string resource. I too face a situation where I need to change locale throughout the app, an the current API does not allow me to do that without every piece of the app knowing what the current locale is.

**Comment by shadyk** [comment]
@IharAndreyeu @abdelmagied94  were you able to have work around regarding this?

**Comment by theScud** [comment]
@tomlokhorst wanted to check with regards to the above comment, setting preferred language globally for the entire app. Is there anything in the roadmap to address this use case ?

**Comment by mobilase** [comment]
Yesterday I change all my strings(~1k) to R.string in my app. In my app I can change language of app.
But after change strings to R.string - change language in app not working.
I need global change of locale. How I can do it? Variant with preferredLanguages does not suit me.

**Comment by mobilase** [comment]
With help of [Article: Strong Typed Resources Management with R.swift](https://medium.com/@dayton159/strong-typed-resources-management-with-r-swift-1e3c8093ea41) - I found my workaround.

I create module Languages (where enum Languages and extension R)

```
import Foundation
import Localize_Swift
import Rswift

enum Languages: String {
    case ru
    case en
    case lt
    case lv
    case et
}

extension Languages {
    var langcode: String {
        switch self {
        case .en:
            return "en"
        case .ru:
            return "ru-RU"
        case .lt:
            return "lt-LT"
        case .lv:
            return "lv-LV"
        case .et:
            return "et-EE"
        }
    }
    
    static private var preffered: Languages = Languages.en
    static private var langBundle: Bundle?
    
    static func getLang() -> String {
        return preffered.langcode
    }
    
    static func setLang(_ langCode: String) {
        preffered = Languages(rawValue: langCode) ?? Languages.en
        let url = Bundle(for: R.ClassR.self).url(forResource: preffered.langcode, withExtension: "lproj")
        langBundle = Bundle(url: url!)
    }
    
    static func getBundle() -> Bundle? {
        if (langBundle == nil) {
            let url = Bundle(for: R.ClassR.self).url(forResource: preffered.langcode, withExtension: "lproj")
            langBundle = Bundle(url: url!)
        }
        return langBundle
    }
    
    static func getName(_ code: String) -> String {
        let locale : NSLocale = NSLocale(localeIdentifier: code)
        return locale.displayName(forKey: NSLocale.Key.identifier, value: code) ?? code
    }
    
    static func getLocalName(_ code: String) -> String {
        return Localize.displayNameForLanguage(code)
    }
}

extension R {
    static var text = R.string.localizable.self
    
    fileprivate class ClassR {}
    
    static func local(_ string: StringResource) -> String {
        return NSLocalizedString("\(string.key)", bundle: Languages.getBundle()!, comment: "")
    }
}
``` 

And when I change language of app I run this:
```
Languages.setLang(langCode)
```

And strings...
Before R.swift:
```
"test".localized()
```
With standard R.swift:
```
R.string.localizable.test()
```
With my workaround:
```
R.local(R.text.test)
```

**Pull request merged**
