### PR TITLE
Parse color palette files

### PR DESCRIPTION
**Pull request by tomlokhorst**
Implements https://github.com/mac-cain13/R.swift/issues/169

- [x] Add comments to generated code (including hex string)
- [x] Add tests to check if all conversions between colors works correctly

### CODE REVIEW

**Comment by mac-cain13** [comment]
Looking good to me! :+1: 

One question; What about duplicates? Aswel filenames that result in duplicate identifiers as color names within the files that could create duplicate identifiers.

That's the only thing that maybe could go wrong I think.

**Comment by tomlokhorst** [comment]
Whoops, forgot about those, I've added the code to warn about duplicate identifiers.

**Comment by dxshindeo** [comment]
So is this working? Just added R.swift to my project, but it generates 0 colors (I have no named colors, but I do have custom color palette). Do I have to somehow specify this custom color palette so R.swift generates colors from it?

**Comment by dxshindeo** [comment]
And the reason it was 0 was because: https://github.com/mac-cain13/R.swift/issues/214

**Comment by tomlokhorst** [comment]
Note that `R.clr` is deprecated in favour of `R.color`:
https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-40

Support for color palettes will be removed in a future version of R.swift.

**Comment by dxshindeo** [comment]
_tries not to cry
cries alot_

Thanks for info!

**Pull request merged**
