### PR TITLE
Add conformance to Sendable

### PR DESCRIPTION
**Pull request by g-laures**
Fix the following issue: https://github.com/mac-cain13/R.swift/issues/902

### CODE REVIEW

**Comment by mac-cain13** [comment]
Thanks for the PR, we will solve this by updating the code generator to generate slightly different code that makes the Sendable being inferred by the compiler.

**Comment by letko-dmitry** [comment]
Marking all the types as `Sendable`, guarded by `#if compiler`, remains a better solution as it enables wider usage of the types, rather than simply silencing the warnings.

**Comment by mac-cain13** [comment]
R.swift 7.6 is now released which makes the R type sendable.

**Comment by letko-dmitry** [comment]
But, as far as I understand, to use types in modules, it's still necessary to mark them as `Sendable` explicitly.

**Comment by letko-dmitry** [comment]
And it applies to all types, including those from `RswiftLibrary`.

**Comment by tomlokhorst** [comment]
You are right @letko-dmitry! Thank you for following up on this.

When public structs are generated, it is needed to explicitly conform to Sendable.

(For internal types, the compiler can infer Sendable)

**Pull request closed without merging**
