### PR TITLE
Support ResourceBundles

### PR DESCRIPTION
**Pull request by svendr**
This PR tries to add support for Resource Bundles.

Organizing project resources with Resource Bundles is a fairly common approach in iOS development, especially if you are developing a custom Framework (using Resource Bundles here simplifies integration into client projects heavily). Cocoapods also [encourages using Resource Bundles](https://guides.cocoapods.org/syntax/podspec.html#resources).

R.swift doesn't have native support for loading resources from a Resource Bundle embedded inside a Framework or Executable Target Bundle (Main Bundle). This is a known issue, see #295. I've seen several workarounds manipulating the hostingBundle-definition with sed etc.

So I've introduced the new CLI-parameter **--resourceBundleName**. When given, it changes the hostingBundle from `Bundle(for: R.Class.self)` to `Bundle(url: Bundle(for: R.Class.self).url(forResource: "ResourceBundleName", withExtension: "bundle")!) ?? Bundle(for: R.Class.self)` (replace "ResourceBundleName" with the value of the --resourceBundleName option).

I've successfully tested this with several projects I'm working on.

Glad to hear your thoughts / feedback on this.

### CODE REVIEW

**Comment by moshiwu** [comment]
Great PR, which solve my problem exactly！

**Comment by tomlokhorst** [comment]
Thanks for this PR, it looks great!

I'll test this with some of our projects as well.

**Comment by mac-cain13** [comment]
Nice! Besides the testing @tomlokhorst will perform I think it would be nice to have this documented somewhere and maybe it's possible to create a testcase for this in the ResourceApp we have? If we use it somewhere it's less likely to break.

**Comment by svendr** [comment]
Thanks for your feedback! I'll try to add a test and extend the doc

**Comment by tomlokhorst** [comment]
You can ignore the Bitrise CI error about the failing tests.
The tests aren't properly setup for Xcode 9.

Btw, I tried to test this, but couldn't get it to work...
So I would appreciate some documentation! 😁

**Comment by svendr** [comment]
Hey Tom, I've extended the ResourceApp with 2 new targets

- The `ResourceBundle` target contains some dummy resources
- `ResourceBundleApp` references the `ResourceBundle` build product as target dependency
- `ResourceBundleApp` also calls rswift with the new `--resourceBundleName` option. Important thing here is to also use the `--target` option.

I've also set up a simple unit test and reworked the Podfile to silence several annoying warnings.

I'm still stuck on a problem with `R.validate()`, because it's internals sometimes rely on implicitly referencing the MainBundle. E.g. `StoryboardGenerator.swift` produces code like:

```
static func validate() throws {
        if UIKit.UIImage(named: "User") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'User' is used in storyboard 'Main', but couldn't be loaded.") }
      }
```

But I can't just exchange it with `UIImage(named: "User", bundle: R.hostingBundle)` because the R-struct doesn't exist when building the rswift-Binary. I've also tried to workaround it with Reflection, but had no success. 

I think we would have to extend the R.swift.Library and introduce some kind of `BundleHelper`-struct, which could be accessed from R.generated.swift and be accessed from `StoryboardGenerator.swift` to set / get the `hostingBundle`?

Or do you see a simpler option?

**Comment by tomlokhorst** [comment]
I couldn't quite get this to work in my own CocoaPod with embedded resources.
Could you describe how this is supposed to work?

Does the pod project need a Xcode project with a R.swift build step? Or is this part of the R.swift build step of the application?

**Comment by magrinj** [comment]
@volodg @ANSCoder Hello guys ! What about merging this PR ? :)

**Comment by andlang** [comment]
Would be great to see that feature in the upcoming 5.1.0 release

**Comment by letko-dmitry** [comment]
@svendr any news?

**Comment by yuhanle** [comment]
Good pr, it solve my question.

**Comment by mac-cain13** [comment]
We've looked into this, thanks for all input and discussion around this topic. We think bundles should be properly detected by R.swift and be nested in the R-struct. The design of this will be discussed in https://github.com/mac-cain13/R.swift/issues/186.

I'll close this PR because it will make it hard to use resources in the app itself combined with resources in one or more bundles. Since you then will have 2 structs named `R` in your project.

**Pull request closed without merging**
