### PR TITLE
fix: url(with:) is only availale in iOS 9.0

### PR DESCRIPTION
**Pull request by m-colombo**
Used RSwift with SwiftUI, had to do this to make the preview works. Although I'm not sure this is the proper way of addressing the problem. (Did same PR also on XCodeEdit see https://github.com/tomlokhorst/XcodeEdit/pull/41)

### CODE REVIEW

**Comment by mac-cain13** [comment]
I'm not sure why this fix is necessary, since this is a change in the generator that only runs on macOS and you now add an available-annotation that is for iOS. But the generator never runs on iOS.

Are you sure you've integrated R.swift correctly into your project according to the Readme?

**Comment by m-colombo** [comment]
I honestly don't know whether is my configuration wrong or it's the swiftUI preview tool.
A part from using swift package manager for both project (r.swift and r.swift.library) I followed the readme instruction, it worked both in emulator and physical device, but in the preview tool crashes.

**Comment by mac-cain13** [comment]
Note that you should *NOT* add R.swift itself to your project using SPM, *only* the R.swift.library should be added as a dependency to your project.

**Comment by m-colombo** [comment]
Ou ok, I saw the package.swift and I thought it was fine. Indeed importing it as a pod works. Thanks, sorry to mislead :)

**Pull request closed without merging**
