### PR TITLE
Support for folders providing namespaces in xcassets

### PR DESCRIPTION
**Pull request by amichnia**
Using R.swift i have stumbled upon issue, when using xcassets folders, with "Provides Namespace" checked.

We had xcassets structure in project similar to (all major folders providing namespaces):

- Admin
    - Home
        - ...
    - HowItWorks
        - image1
        - image2
        - ...
    - ... 
- User
    - Home
        - ...
    - HowItWorks
        - image1
        - image2
        - ...
    - ... 

In that case, the correct path for the image is for example: ```Admin/HowItWorks/image1``` - which did not work (R generated just ```image1```).

Another issue was duplicates - in our case, Admin/HowItWorks/image1 was different than User/HowItWorks/image1 - these are two different images, with different names - but R resolved them as duplicates.

I believe that adding namespaces folders support to parsing xcassets is solution, which will also provide a bit more flexibility on how to logically group assets in project.

Major propositions are:
1. If no xcassets subfolders provides namespaces - R should work as it does
2. If xcassets contains folders, that provides namespaces, they should create nested struct. For our case it results in accessing images like ```R.image.Admin.HowItWorks.image1```

In this PR I added necessary model and changed a bit ImageStructureGenerator, to apply to this.

Added:
+ Added namespacd subfolder model in asset folder
+ Added convenience methods for URL
+ Added convenience methods for Array, to merge subfolders from different xcassets
+ Added reporting of conflicting names between images and asset subfolders
+ Added subfolders struct generation

Changed:
* extended AssetFolder with properties files names and extensions
* extended AssetFolder with subfolders, allowing tree structure generation
* extended ImageStructGenerator, allowing to flatten all subfolders providing namespaces from all xcassets folders

### CODE REVIEW

**Comment by amichnia** [comment]
Hello - is there any way to check what is failing on bitrise? I thought it was Swift version (used 3.1, project is for 3.0), but after commit update it still fails. 

I've setup bitrise CI for my fork and runs fastlane runalltests - which seems to pass (stack - Xcode 8.0 on el capitan)

**Comment by tomlokhorst** [comment]
Thanks for your PR!

You can ignore the bitrise error, it currently isn't setup to build pull requests from external repositories.

I haven't looked at the PR in detail yet, but from your description this sounds like a good idea!

Can you include a examples of nested folders in the ResourceApp example project?
Including tests for edge cases like duplicate names.

**Comment by amichnia** [comment]
Thanks for the information - I will update PR with that edge cases and
examples!

If I get it right - I should add emaples that produces warnings (like
naming namespaces folder same as image asset), to ensure that generate code
will compile? I will check current test cases anyway, but wanted to be sure.

Best regards

Andrzej

-- 

*Andrzej Michnia*

*Andrzej Michnia GirAppe Studio*

*[ iOS & game development ]*

dnia 10 maja 2017 o 21:17:07, Tom Lokhorst (notifications@github.com)
napisał:

Thanks for your PR!

You can ignore the bitrise error, it currently isn't setup to build pull
requests from external repositories.

I haven't looked at the PR in detail yet, but from your description this
sounds like a good idea!

Can you include a examples of nested folders in the ResourceApp example
project?
Including tests for edge cases like duplicate names.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mac-cain13/R.swift/pull/325#issuecomment-300585258>,
or mute
the thread

**Comment by amichnia** [comment]
I have added tests (basically - two more warnings check) for edge cases:

1. Two xcassets folders, with same namespaces subfolder, containing conflicting images
2. Conflict between image name (Uppercased) and namespaces subfolder name - struct generation skipped and warning produced
3. Two xcassets folders, with same namespaces subfolder should not produce warning, their contents are merged, as long as the images are different

**Comment by amichnia** [comment]
Hello, what is status of that issue?

**Comment by tomlokhorst** [comment]
Hi, sorry about not replying sooner.
I'm a bit busy with other things at the moment.

I tested your branch a few days ago, and everything seemed to work correctly!
I want to do a bit more testing, including testing this branch in a bunch of existing projects with lots of images.
If everything continues to work, I'll merge this branch and this feature will be in the next R.swift release.

Thanks a lot for your work so far!

**Comment by rafalwojcik** [comment]
Nice work @amichnia !!! I can't wait for new R.swift release

**Comment by mac-cain13** [comment]
@rafalwojcik Good news! This is in the R.swift 3.3.0 release!

**Pull request merged**
