### PR TITLE
R.swift 7 – Major version, Xcode plugin, internal refactor

### PR DESCRIPTION
**Pull request by tomlokhorst**
⚠️ This is a test version of a new version major of R.swift.

Global overview:

 - Refactored internals (therefore: breaking changes)
 - Merged R.swift and R.swift.Library projects
 - Smaller generated code
 - A lot of fixes to open issues
 - SPM Plugin support

This version still needs testing in real world projects, to see if there are things broken that shouldn't be. Also a proper migration guide needs to be written.

---

If you want to help testing this version in your project:

CocoaPods:
`pod 'R.swift', '~> 7.0.0-alpha.17'`
SPM:
`.package(url: "https://github.com/mac-cain13/R.swift.git", branch: "refactor")`

---

Fixes:
 - fixes https://github.com/mac-cain13/R.swift/issues/48
 - fixes https://github.com/mac-cain13/R.swift/issues/102
 - fixes https://github.com/mac-cain13/R.swift/issues/136
 - fixes https://github.com/mac-cain13/R.swift/issues/155
 - fixes https://github.com/mac-cain13/R.swift/issues/252
 - fixes https://github.com/mac-cain13/R.swift/issues/454
 - fixes https://github.com/mac-cain13/R.swift/issues/511
 - closes https://github.com/mac-cain13/R.swift/pull/564
 - closes https://github.com/mac-cain13/R.swift/pull/588
 - closes https://github.com/mac-cain13/R.swift/pull/589
 - fixes https://github.com/mac-cain13/R.swift/issues/591
 - fixes https://github.com/mac-cain13/R.swift/issues/600
 - fixes https://github.com/mac-cain13/R.swift/issues/608
 - fixes https://github.com/mac-cain13/R.swift/issues/617
 - fixes https://github.com/mac-cain13/R.swift/issues/634
 - closes https://github.com/mac-cain13/R.swift/pull/639
 - closes https://github.com/mac-cain13/R.swift/pull/693
 - fixes https://github.com/mac-cain13/R.swift/issues/695
 - closes https://github.com/mac-cain13/R.swift/pull/705
 - fixes https://github.com/mac-cain13/R.swift/issues/707
 - fixes https://github.com/mac-cain13/R.swift/issues/709
 - fixes https://github.com/mac-cain13/R.swift/issues/710
 - fixes https://github.com/mac-cain13/R.swift/issues/714
 - fixes https://github.com/mac-cain13/R.swift/issues/735
 - fixes https://github.com/mac-cain13/R.swift/issues/738
 - fixes https://github.com/mac-cain13/R.swift/issues/742
 - fixes https://github.com/mac-cain13/R.swift/issues/747
 - closes https://github.com/mac-cain13/R.swift/pull/749
 - fixes https://github.com/mac-cain13/R.swift/issues/754
 - fixes https://github.com/mac-cain13/R.swift/issues/760
 - closes https://github.com/mac-cain13/R.swift/pull/761

### CODE REVIEW

**Comment by RobertDresler** [comment]
Hello, I wanted to implement R.swift 7 to my package. So I added it to the package as you described
```
.package(url: "https://github.com/mac-cain13/R.swift.git", branch: "refactor")
```

No I was able to see the plugins, but just two of them:

Screenshot 2022-11-09 at 12 03 23

Anyway, I gave it a try and I called the generate plugin which successfully created `R.generated.swift` for me. But now I received another error as you see below, it says `Cannot find type 'ImageResource' in scope`

Screenshot 2022-11-09 at 12 02 52

So I have two questions:
1. Do I do something wrong that I don't see other plugins like the one for generating public resources (`RswiftGeneratePublicResources`)?
2. Do I do something wrong that `R.generated` doesn't know about `ImageResource `?

Thank you very much for you help and your work!

**Comment by tomlokhorst** [comment]
@RobertDresler Thanks for testing this version!

There are two types of plugin, Command plugins that you manually need to call (like `RswiftGenerateResourcesCommand`) and Build plugins that can be run on every build (like `RswiftGeneratePublicResources`).

You can configure the build plugin in Xcode from the target "Build Phases" tab, in the "Run Build Tool Plug-ins" section:

Run Build Tool Plug-ins (Rswift)

NOTE: For some reason, sometimes just adding the build tool there doesn't actually run it when building the project (I don't know why). That's why I added the `RswiftModifyXcodePackages` that can be run ones, it fixes up the Xcode project file, to make the build tool work.

As for the error about the ImageResource not being found. That seems to be an error in the generated code, I'll fix that in the next version.

**Comment by RobertDresler** [comment]
@tomlokhorst thank you, I was able to generate public resources by adding `dependencies: [.product(name: "RswiftLibrary", package: "R.swift")]` and `plugins: [.plugin(name: "RswiftGeneratePublicResources", package: "R.swift")]`  to my target as you suggested!

About `ImageResource`, I'll wait until you fix it. BTW Thank you for your very fast response, I wasn't expecting it that fast 😄

**Comment by tomlokhorst** [comment]
The latest commit should fix the missing import for `ImageResource`.

**Comment by RobertDresler** [comment]
@tomlokhorst ok, thank you. Public image resources as well as strings works for me like a charm! 🎉

**Comment by RobertDresler** [comment]
Hello, thats me again. I'm now trying to perform my first clean build of the app using new R.swift on Bitrise using Fastlane and I run into this issue

```
The following build commands failed:
	Validate plug-in “RswiftGeneratePublicResources” in package “r.swift”
```

Don't you have any idea what could cause this problem?

**Comment by RobertDresler** [comment]
@tomlokhorst thanks! Adding `-skipPackagePluginValidation` to `xcodebuild` fixed that for me!

For future readers who use Fastlane; add it to `xcargs` to `build_app`:

```
build_app(
  ...
  xcargs: "-skipPackagePluginValidation"
  ...
)
```

**Comment by kemchenj** [comment]
One small thought, instead of maintaining the existing code-generating code, maybe we could use [SwiftSyntax](https://github.com/apple/swift-syntax) to generate code.

**Comment by tomlokhorst** [comment]
Demo video: Updating from R.swift 6 to 7:
https://www.youtube.com/watch?v=icihJ_hin3I

**Pull request merged**
