### PR TITLE
Development pods output file validation fix

### LINKED ISSUE #475: Output files validation
I was trying to set up R.swift 5.0.0 in my development pod that is placed in `project_root/Development Pods/pod_name` and got an error `[R.swift] Build phase Output Files do not contain '$SRCROOT/../Development Pods/pod_name/pod_name/Classes/R.generated.swift'.`

The problem is in `EnvironmentValidation.swift:45` where path strings are compared. In my case, `outputURL.path =  project_root/Pods/../Development Pods/pod_name/pod_name/Classes/R.generated.swift` and `scriptOutputFile = project_root/Development Pods/pod_name/pod_name/Classes/R.generated.swift` which both represents single path but strings are different

### PR DESCRIPTION
**Pull request by Salfetamen**
#475 fix

### CODE REVIEW

**Comment by Yuop** [comment]
@mac-cain13, gotta merge it!

**Comment by tomlokhorst** [comment]
I've updated the PR with a separate fix to XcodeEdit that included some path changes.

Also, the $PODS_TARGET_SRCROOT is now shown in error messages.

@Salfetamen Could you check if this still works with your project? If so, I'll merge this and it'll be in the next release.

**Comment by Salfetamen** [comment]
@tomlokhorst It works

**Comment by tomlokhorst** [comment]
@mac-cain13 Note the rswift binary now requires OS X 10.11:

`swift build -c release -Xswiftc -static-stdlib -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.11"`

**Comment by svendr** [comment]
I ran into this problem, too.

The simple solution was to just reference the output-file in the run script itself.

So instead of `"$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/Example/R.generated.swift"` you should just call `"$PODS_ROOT/R.swift/rswift" generate "$SCRIPT_OUTPUT_FILE_0"`

**Comment by RafaelPlantard** [comment]
I will try it @svendr

**Comment by tomlokhorst** [comment]
5.0.1 with this fix has been released.

**Pull request merged**
