### PR TITLE
Add basic watchos support

### PR DESCRIPTION
**Pull request by lammertw**
Depends on https://github.com/mac-cain13/R.swift.Library/pull/28

Add a Watch app and extension using R.swift to the sample application.

### CODE REVIEW

**Comment by lammertw** [comment]
I was wondering about the state of this PR. Is it being considered for inclusion. We're now using my fork in our projects and would love to go back to the non forked release.

**Comment by tomlokhorst** [comment]
Hi, thank you for your PR, and sorry for the (very) late reply.

We are interested in adding watchOS support, and merging this PR, but we've been very busy these last few months. When we've finally figured out a good fix for [the issues with the New Build System](https://github.com/mac-cain13/R.swift/issues/456) we'll have some time to look add merging new features.

Again, thank you for this PR!

**Comment by teameh** [comment]
Any updates on this? We've quite a big project stuck on the 5.0.0 alpha release branch from @lammertw because we need watchOS support. Anything I can do to help get this merged :) ?

**Comment by tomlokhorst** [comment]
No updates, other than that we did manage to figure out the build system issues and R.swift 5 has been released (5.0.3 now).

I do plan on looking at this PR (and others), but after WWDC, once we know if there's major changes in the next Xcode.

**Comment by tomlokhorst** [comment]
Thanks again for this PR!
Sorry it took so long, we were busy with other stuff. 

I've merged it and it will be part of the next R.swift release.

**Pull request merged**
